{"name":"Test_Login_Unsuccessful","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [warning: no match for e-mail address and/or password.] but found [warning: your account has exceeded allowed number of login attempts. please try again in 1 hour.]","trace":"java.lang.AssertionError: expected [warning: no match for e-mail address and/or password.] but found [warning: your account has exceeded allowed number of login attempts. please try again in 1 hour.]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:575)\r\n\tat org.testng.Assert.assertEquals(Assert.java:585)\r\n\tat testAccount.Test_Login_Unsuccessful(testAccount.java:81)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","description":"Validate that the login is working with non validad credentials","steps":[],"attachments":[],"parameters":[],"start":1628520598635,"stop":1628520604991,"uuid":"47d1dc7b-6e03-40cf-9273-12c03901f33f","historyId":"727da1cfebfc3db029c324fef45a807f","fullName":"testAccount.Test_Login_Unsuccessful","labels":[{"name":"package","value":"testAccount"},{"name":"testClass","value":"testAccount"},{"name":"testMethod","value":"Test_Login_Unsuccessful"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"FRAMEWORK_SELENIUM"},{"name":"subSuite","value":"testAccount"},{"name":"host","value":"NACHOTIC"},{"name":"thread","value":"6044@NACHOTIC.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}